name: Build EXE

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create data directory if not exists
      run: |
        if (!(Test-Path "data")) { New-Item -ItemType Directory -Path "data" }
        
    - name: Build EXE
      run: |
        pyinstaller main.spec
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MaiLauncher-Backend-${{ github.sha }}
        path: |
          dist/MaiLauncher-Backend.exe
        retention-days: 30
        
    - name: Create Release (on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: Auto Build ${{ github.run_number }}
        body: |
          Automated build from commit ${{ github.sha }}
          
          Changes in this build:
          ${{ github.event.head_commit.message }}
        files: |
          dist/MaiLauncher-Backend.exe
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
